### ISSUE TITLE
Download from Cachix don't work on NixOS

### ISSUE THREAD

**Issue by davidak** [ryantm/nixpkgs-update#93]
## Expected behaviour

Just copy and paste the code and get the store-path.

## Actual behaviour

Some errors:
```
[davidak@ethmoid:~]$ nix-store -r /nix/store/nnjwfihp95z1d7dyi6npbvlqrvkicgnj-bacula-9.2.2 \
>   --option binary-caches 'https://cache.nixos.org/ https://r-ryantm.cachix.org/' \
>   --option trusted-public-keys '
>   r-ryantm.cachix.org-1:gkUbLkouDAyvBdpBX0JOdIiD2/DP1ldF3Z3Y6Gqcc4c=
>   cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
>   '
warning: ignoring untrusted substituter 'https://r-ryantm.cachix.org/'
don't know how to build these paths:
  /nix/store/nnjwfihp95z1d7dyi6npbvlqrvkicgnj-bacula-9.2.2
error: build of '/nix/store/nnjwfihp95z1d7dyi6npbvlqrvkicgnj-bacula-9.2.2' failed
```

---

nix (Nix) 2.1.3

**Comment by ryantm** [comment]
@davidak  thanks for the report. It seems like there is some issue with Cachix uploading some, or all of the result paths. I need to investigate this some more.

In the meantime, I uploaded the paths for `bacula`, so it should work now.

**Comment by davidak** [comment]
Yes, works now.

```
[davidak@ethmoid:~]$ nix-store -r /nix/store/nnjwfihp95z1d7dyi6npbvlqrvkicgnj-bacula-9.2.2 \
>    --option binary-caches 'https://cache.nixos.org/ https://r-ryantm.cachix.org/' \
>    --option trusted-public-keys '
>    r-ryantm.cachix.org-1:gkUbLkouDAyvBdpBX0JOdIiD2/DP1ldF3Z3Y6Gqcc4c=
>    cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
>    '
warning: ignoring untrusted substituter 'https://r-ryantm.cachix.org/'
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/nnjwfihp95z1d7dyi6npbvlqrvkicgnj-bacula-9.2.2

```

**Comment by ryantm** [comment]
This hasn't been a recurring issue, so closing for now.

**Comment by das-g** [comment]
This does still happen to me if I don't run the `nix-store` command as `root` or with `sudo`.

**Comment by davidak** [comment]
I see this issue again with all packages i tested:

https://github.com/NixOS/nixpkgs/pull/75313
https://github.com/NixOS/nixpkgs/pull/75316
https://github.com/NixOS/nixpkgs/pull/75341

For example:

```
[davidak@X230:~]$ nix-store -r /nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14 \
>   --option binary-caches 'https://cache.nixos.org/ https://r-ryantm.cachix.org/' \
>   --option trusted-public-keys '
>   r-ryantm.cachix.org-1:gkUbLkouDAyvBdpBX0JOdIiD2/DP1ldF3Z3Y6Gqcc4c=
>   cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
>   '
warning: ignoring untrusted substituter 'https://r-ryantm.cachix.org/'
warning: ignoring the user-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
don't know how to build these paths:
  /nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14
error: build of '/nix/store/cm3p4qb5kw3ihklx2fm6l53adflfv4k2-python3.8-funcy-1.14' failed
```

**Comment by das-g** [comment]
Does running the command as root or with `sudo` work for you , @davidak? (It does for me.)

**Comment by davidak** [comment]
>Does running the command as root or with sudo work for you

yes (tested with sudo)
